# Generated by Django 2.2.11 on 2020-04-07 17:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_auto_20200407_1244"),
    ]

    operations = [
        migrations.RemoveField(model_name="provider", name="city",),
        migrations.RemoveField(model_name="provider", name="state",),
        migrations.AlterField(
            model_name="provider",
            name="pre_packaged_meal_price",
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=14),
        ),
    ]
