# Generated by Django 2.2.11 on 2020-04-07 17:16
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_auto_20200407_1302"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order", options={"ordering": ["-deliver_on", "id"]},
        ),
        migrations.RemoveField(model_name="order", name="name",),
        migrations.AlterField(
            model_name="consumer",
            name="city",
            field=models.TextField(default="Columbus"),
        ),
        migrations.AlterField(
            model_name="consumer", name="state", field=models.TextField(default="OH"),
        ),
    ]
