# Generated by Django 2.2.11 on 2020-04-07 17:24
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_auto_20200407_1316"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="need_delivery",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
