# Generated by Django 2.2.11 on 2020-04-07 17:58
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_order_need_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer", name="name", field=models.CharField(max_length=1024),
        ),
    ]
