# Generated by Django 2.2.11 on 2020-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_auto_20200407_1402"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consumer", name="phone", field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="provider", name="phone", field=models.CharField(max_length=20),
        ),
    ]
